name: deploy

on:
  push:
    branches:
      - test/simonandresguijarromurrieta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Set Railway Token
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

      - name: Deploy Monolith
        run: railway up --service fullstack_test_01 --ci --verbose