name: Monolith Deploy - Railway

on:
  push:
    branches:
      - test/simonandresguijarromurrieta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Auth Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Monolith
        run: railway up --ci --verbose
